### ISSUE TITLE
Move to maven build

### ISSUE THREAD

**Issue by rjpower4** [Adaptive-Trajectory-Design/atd-core#2]
We should probably move to some sort of build tool to be consistent in how we're generating JARs as well as where we put them independent of an IDE. 

From what I see I feel like Maven might be a good option for this. Ideas?

**Comment by adcox** [comment]
Agreed - independence from a specific IDE is a good thing to strive for. I haven't really ever done that, though, so your ideas are as good as mine.

**Comment by rjpower4** [comment]
Looking at it, it looks like it would make sense to re-organize the layout (Maven has some standard layouts which will probably help us in the long term). Therefore, it might make sense to table this until we migrate to the GitLab repo and do the refactoring then.

**Comment by adcox** [comment]
Sounds good!

**Comment by adcox** [comment]
As of most recent commit (498c71fff7e31d5fe35c9230ccbc79ac8de0f39d), Maven build works on Windows, Linux, and Apple OS.

@rjpower4 We can probably close this issue?

**Comment by rjpower4** [comment]
Yeah, I think so!
